name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - "back-end/**"
      - ".github/workflows/azure-backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./back-end
        run: npm i

      - "start": "ls -1t /home/data/SitePackages/*.zip | tail -n +2 | xargs rm -rf && node server.js"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: CNE-groep7-back-end
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
          package: ./back-end
