name: Deploy Functions and Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "CNE-group7-functions" # function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "back-end" # set this to the path to our function app project
  NODE_VERSION: "20.x"

jobs:
  upload-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Upload Environment Variables
        run: |
          echo "Storage Account: $AZURE_STORAGE_ACCOUNT"
          echo "Container: $AZURE_STORAGE_CONTAINER"
          echo "SAS token is set: ${AZURE_STORAGE_SAS_TOKEN:+yes}"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

      - name: Run Upload Script
        run: |
          chmod +x ./upload-site.sh
          ./upload-site.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

  build-and-deploy-functions:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      #   - name: "Resolve Project Dependencies Using Npm"
      #     shell: pwsh
      #     run: |
      #       pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      #       npm install
      #       npm run build --if-present
      #       npm run test --if-present
      #       popd

      - name: "Resolve Project Dependencies Using Npm"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
