name: Deploy Functions and Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "CNE-group7-functions" # function app name on Azure
  NODE_VERSION: "20.x"
  BUILD_OUTPUT_DIR: "dist"  # New build output directory

jobs:
  upload-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          node-version: '18'
        
      - name: Install dependencies
        run: |
          cd front-end
          npm install
          
      - name: Set production API URL
        run: echo "NEXT_PUBLIC_API_URL=https://cne-group7-functions.azurewebsites.net/api" > front-end/.env.production

      - name: Build frontend
        run: |
          cd front-end
          npm run build
          npm run export
        env:
          NODE_ENV: production
          
      - name: Install jq for URL encoding
        run: sudo apt-get install -y jq
      
      - name: Run Upload Script
        run: |
          chmod +x ./upload-site.sh
          ./upload-site.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

  build-and-deploy-functions:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
        env:
          AZURE_FUNCTIONS_ENVIRONMENT: 'production'

      - name: Verify Build Output
        run: |
          ls -la ${{ env.BUILD_OUTPUT_DIR }}
          echo "Build output contains:"
          find ${{ env.BUILD_OUTPUT_DIR }} -type f | sort

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./dist
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
